"""Initial schema with contracts, partners, orders, templates, idempotency

Revision ID: 84a918765626
Revises:
Create Date: 2025-08-08 22:11:54.558574

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84a918765626"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_number", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract")),
    )
    op.create_index(
        op.f("ix_contract_contract_number"), "contract", ["contract_number"], unique=True
    )
    op.create_index(op.f("ix_contract_id"), "contract", ["id"], unique=False)
    op.create_table(
        "folder_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("template_type", sa.String(length=50), nullable=False),
        sa.Column("folder_structure", sa.JSON(), nullable=False),
        sa.Column("permissions_template", sa.JSON(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["folder_template.id"],
            name=op.f("fk_folder_template_parent_id_folder_template"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_folder_template")),
    )
    op.create_index(op.f("ix_folder_template_id"), "folder_template", ["id"], unique=False)
    op.create_table(
        "idempotent_operation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("em_id", sa.String(length=50), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("scope", sa.String(length=255), nullable=False),
        sa.Column("timestamp_window", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotent_operation")),
    )
    op.create_index(
        "ix_idempotent_operation_composite",
        "idempotent_operation",
        ["em_id", "operation", "scope", "timestamp_window"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotent_operation_id"), "idempotent_operation", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_idempotent_operation_idempotency_key"),
        "idempotent_operation",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "partner_company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=False),
        sa.Column("tax_number", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partner_company")),
    )
    op.create_index(
        op.f("ix_partner_company_company_code"), "partner_company", ["company_code"], unique=True
    )
    op.create_index(op.f("ix_partner_company_id"), "partner_company", ["id"], unique=False)
    op.create_table(
        "order_em",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("em_number", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("partner_company_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("part", sa.String(length=1), nullable=False),
        sa.Column("team_name", sa.String(length=255), nullable=True),
        sa.Column("site_url", sa.String(length=500), nullable=True),
        sa.Column("provisioning_status", sa.String(length=50), nullable=False),
        sa.Column("provisioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_status", sa.String(length=50), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"], ["contract.id"], name=op.f("fk_order_em_contract_id_contract")
        ),
        sa.ForeignKeyConstraint(
            ["partner_company_id"],
            ["partner_company.id"],
            name=op.f("fk_order_em_partner_company_id_partner_company"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_em")),
    )
    op.create_index(op.f("ix_order_em_em_number"), "order_em", ["em_number"], unique=True)
    op.create_index(op.f("ix_order_em_id"), "order_em", ["id"], unique=False)
    op.create_index(op.f("ix_order_em_year"), "order_em", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_em_year"), table_name="order_em")
    op.drop_index(op.f("ix_order_em_id"), table_name="order_em")
    op.drop_index(op.f("ix_order_em_em_number"), table_name="order_em")
    op.drop_table("order_em")
    op.drop_index(op.f("ix_partner_company_id"), table_name="partner_company")
    op.drop_index(op.f("ix_partner_company_company_code"), table_name="partner_company")
    op.drop_table("partner_company")
    op.drop_index(
        op.f("ix_idempotent_operation_idempotency_key"), table_name="idempotent_operation"
    )
    op.drop_index(op.f("ix_idempotent_operation_id"), table_name="idempotent_operation")
    op.drop_index("ix_idempotent_operation_composite", table_name="idempotent_operation")
    op.drop_table("idempotent_operation")
    op.drop_index(op.f("ix_folder_template_id"), table_name="folder_template")
    op.drop_table("folder_template")
    op.drop_index(op.f("ix_contract_id"), table_name="contract")
    op.drop_index(op.f("ix_contract_contract_number"), table_name="contract")
    op.drop_table("contract")
    # ### end Alembic commands ###
